server:
  port: 8081
  servlet:
    context-path: /api

spring:
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/awesome_job?stringtype=unspecified
    username: postgres
    password: 123456
    hikari:
      connectionTimeout: 30000
      minimumIdle: 12
      maximumPoolSize: 50
      idleTimeout: 600000
      maxLifetime: 1800000
      autoCommit: true
      leakDetectionThreshold: 60000
  main:
    allow-bean-definition-overriding: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    serialization:
      write-dates-as-timestamps: true
  jpa:
    hibernate:
      ddl-auto: none
logging:
  config: config/log4j2.yml
  level:
    vn:
      com:
        tech:
          userid:
            connector: DEBUG
    org:
      springframework:
        web: info
        kafka:
          listener: off
      apache:
        kafka: off
      hibernate:
        SQL: off
      type:
        descriptor:
          sql: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      log-format: "connectionId: %(connectionId) | executionTime:  %(executionTime)ms | type: %(category)\n%(sql)"
